// GENERATED from assets/design/data.js — sample catalog for the Fake* repositories.
// Covers and track lists are real (iTunes Search API, used for demo purposes).

class SampleAlbum {
  const SampleAlbum({
    required this.id,
    required this.title,
    required this.artist,
    required this.year,
    required this.genre,
    required this.cover,
    required this.palette,
    required this.tracks,
  });
  final String id;
  final String title;
  final String artist;
  final int year;
  final String genre;
  final String cover;
  final List<int> palette;
  final List<SampleTrack> tracks;
}

class SampleTrack {
  const SampleTrack(this.id, this.title, this.seconds);
  final String id;
  final String title;
  final int seconds;
}

const sampleAlbums = <SampleAlbum>[
  SampleAlbum(
    id: 'deja',
    title: 'Deja',
    artist: 'Bomba Estéreo',
    year: 2021,
    genre: 'Pop en español',
    cover: 'assets/images/covers/deja.jpg',
    palette: [0xFF718933, 0xFF667F37, 0xFFEAEFF3],
    tracks: [
      SampleTrack('deja-1', 'Agua', 201),
      SampleTrack('deja-2', 'Deja', 231),
      SampleTrack('deja-3', 'Como Lo Pedí', 245),
      SampleTrack('deja-4', 'Soledad', 217),
      SampleTrack('deja-5', 'Se Acabó', 221),
      SampleTrack('deja-6', 'Conexión Total', 215),
      SampleTrack('deja-7', 'Tamborero', 254),
      SampleTrack('deja-8', 'Lento', 155),
      SampleTrack('deja-9', 'Tierra', 211),
      SampleTrack('deja-10', 'Amor Amor', 184),
      SampleTrack('deja-11', 'Profundo', 224),
      SampleTrack('deja-12', 'Ahora', 274),
      SampleTrack(
        'deja-13',
        'Mamo Manuel Nieves (Sierra Nevada de Santa Marta)',
        158,
      ),
    ],
  ),
  SampleAlbum(
    id: 'ayo',
    title: 'Ayo',
    artist: 'Bomba Estéreo',
    year: 2017,
    genre: 'Pop en español',
    cover: 'assets/images/covers/ayo.jpg',
    palette: [0xFFFD8381, 0xFFF98280, 0xFFD59A9B],
    tracks: [
      SampleTrack('ayo-1', 'Siembra', 258),
      SampleTrack('ayo-2', 'Ayo', 173),
      SampleTrack(
        'ayo-3',
        'Química (Dance With Me) [feat. Balkan Beat Box]',
        162,
      ),
      SampleTrack('ayo-4', 'Duele', 224),
      SampleTrack('ayo-5', 'Amar Así', 237),
      SampleTrack('ayo-6', 'Money Money Money...', 168),
      SampleTrack('ayo-7', 'Internacionales', 188),
      SampleTrack('ayo-8', 'Flower Power', 199),
      SampleTrack('ayo-9', 'Taganga', 165),
      SampleTrack('ayo-10', 'Vuelve', 311),
    ],
  ),
  SampleAlbum(
    id: 'amanecer',
    title: 'Amanecer',
    artist: 'Bomba Estéreo',
    year: 2015,
    genre: 'Pop en español',
    cover: 'assets/images/covers/amanecer.jpg',
    palette: [0xFFD0473B, 0xFFCF5153, 0xFF534B54],
    tracks: [
      SampleTrack('amanecer-1', 'Amanecer', 249),
      SampleTrack('amanecer-2', 'Caderas', 176),
      SampleTrack('amanecer-3', 'Somos Dos', 240),
      SampleTrack('amanecer-4', 'Soy Yo', 160),
      SampleTrack('amanecer-5', 'Fiesta', 219),
      SampleTrack('amanecer-6', 'Voy', 196),
      SampleTrack('amanecer-7', 'Algo Está Cambiando', 270),
      SampleTrack('amanecer-8', 'Mar (Lo Que Siento)', 230),
      SampleTrack('amanecer-9', 'To My Love', 240),
      SampleTrack('amanecer-10', 'Sólo Tú', 255),
      SampleTrack('amanecer-11', 'Raíz', 219),
    ],
  ),
  SampleAlbum(
    id: 'pipa',
    title: 'La Pipa de la Paz',
    artist: 'Aterciopelados',
    year: 1996,
    genre: 'Alternativa y rock en español',
    cover: 'assets/images/covers/pipa.jpg',
    palette: [0xFFC88958, 0xFF59A498, 0xFF909D8E],
    tracks: [
      SampleTrack('pipa-1', 'Cosita Seria', 208),
      SampleTrack('pipa-2', 'No Necesito', 224),
      SampleTrack('pipa-3', 'Quemarropa', 206),
      SampleTrack('pipa-4', 'Nada Quer Ver', 200),
      SampleTrack('pipa-5', 'La Culpable', 201),
      SampleTrack('pipa-6', 'Expreso Amazonia', 227),
      SampleTrack('pipa-7', 'Miss Panela', 228),
      SampleTrack('pipa-8', 'Música', 210),
      SampleTrack('pipa-9', 'Buena Estrella', 206),
      SampleTrack('pipa-10', 'Baracunatana', 152),
      SampleTrack('pipa-11', 'Platonico', 215),
      SampleTrack('pipa-12', 'La Voz de la Patria', 229),
      SampleTrack('pipa-13', 'Chica Difícil', 144),
      SampleTrack('pipa-14', 'Te Juro Que No', 209),
      SampleTrack('pipa-15', 'La Pipa de la Paz', 280),
    ],
  ),
  SampleAlbum(
    id: 'vives',
    title: 'La Tierra del Olvido',
    artist: 'Carlos Vives',
    year: 1995,
    genre: 'Música tropical',
    cover: 'assets/images/covers/vives.jpg',
    palette: [0xFFD56D31, 0xFF854E37, 0xFF736463],
    tracks: [
      SampleTrack('vives-1', 'Pa\' Mayte', 189),
      SampleTrack('vives-2', 'Fidelina', 262),
      SampleTrack('vives-3', 'La Tierra del Olvido', 266),
      SampleTrack('vives-4', 'Zoila', 264),
      SampleTrack('vives-5', 'Rosa', 253),
      SampleTrack('vives-6', 'Agua', 233),
      SampleTrack('vives-7', 'La Cachucha Bacana', 261),
      SampleTrack('vives-8', 'Diosa Coronada', 254),
      SampleTrack('vives-9', 'La Puya Puya', 300),
      SampleTrack('vives-10', 'Ella', 227),
      SampleTrack('vives-11', 'Jam en Jukumey', 93),
    ],
  ),
  SampleAlbum(
    id: 'shakira',
    title: 'Pies Descalzos',
    artist: 'Shakira',
    year: 1995,
    genre: 'Latin',
    cover: 'assets/images/covers/shakira.jpg',
    palette: [0xFFD3A488, 0xFFAC8772, 0xFF402A27],
    tracks: [
      SampleTrack('shakira-1', 'Estoy Aquí', 232),
      SampleTrack('shakira-2', 'Antología', 254),
      SampleTrack('shakira-3', 'Un Poco de Amor', 241),
      SampleTrack('shakira-4', 'Quiero', 250),
      SampleTrack('shakira-5', 'Te Necesito', 240),
      SampleTrack('shakira-6', 'Vuelve', 234),
      SampleTrack('shakira-7', 'Te Espero Sentada', 205),
      SampleTrack('shakira-8', 'Pies Descalzos, Sueños Blancos', 206),
      SampleTrack('shakira-9', 'Pienso en Ti', 146),
      SampleTrack('shakira-10', 'Dónde Estás Corazón', 232),
      SampleTrack('shakira-11', 'Se Quiere, Se Mata', 218),
    ],
  ),
  SampleAlbum(
    id: 'juanes',
    title: 'Mi Sangre',
    artist: 'Juanes',
    year: 2004,
    genre: 'Latin',
    cover: 'assets/images/covers/juanes.jpg',
    palette: [0xFFAF683F, 0xFF663218, 0xFF8D8D8D],
    tracks: [
      SampleTrack('juanes-1', 'Ámame', 260),
      SampleTrack('juanes-2', 'Para Tu Amor', 249),
      SampleTrack('juanes-3', 'Sueños', 190),
      SampleTrack('juanes-4', 'La Camisa Negra', 217),
      SampleTrack('juanes-5', 'Nada Valgo Sin Tu Amor', 196),
      SampleTrack('juanes-6', 'No Siento Penas', 233),
      SampleTrack('juanes-7', 'Dámelo', 247),
      SampleTrack('juanes-8', 'Lo Que Me Gusta a Mí', 211),
      SampleTrack('juanes-9', 'Rosarío Tijeras', 207),
      SampleTrack('juanes-10', '¿Qué Pasa?', 228),
      SampleTrack('juanes-11', 'Volverte a Ver', 218),
      SampleTrack('juanes-12', 'Tu Guardián', 266),
    ],
  ),
  SampleAlbum(
    id: 'mperine',
    title: 'Caja de Música',
    artist: 'Monsieur Periné',
    year: 2015,
    genre: 'Latin Jazz',
    cover: 'assets/images/covers/mperine.jpg',
    palette: [0xFFB8B0A8, 0xFF5D5554, 0xFFDFE0E0],
    tracks: [
      SampleTrack('mperine-1', 'Nuestra Canción (feat. Vicente García)', 260),
      SampleTrack('mperine-2', 'No Hace Falta', 222),
      SampleTrack('mperine-3', 'Tu M\'as Promis', 328),
      SampleTrack('mperine-4', 'Interludio: Carillons À Musique', 51),
      SampleTrack('mperine-5', 'Turquesa Menina', 180),
      SampleTrack('mperine-6', 'Déjame Vivir', 214),
      SampleTrack('mperine-7', 'Año Bisiesto', 235),
      SampleTrack('mperine-8', 'Viejos Amores', 170),
      SampleTrack('mperine-9', 'Incendio', 220),
      SampleTrack('mperine-10', 'Marinero Wawani', 251),
      SampleTrack('mperine-11', 'Lloré', 232),
      SampleTrack('mperine-12', 'Mi Libertad', 337),
      SampleTrack('mperine-13', 'Outro: Caja de Música', 105),
    ],
  ),
  SampleAlbum(
    id: 'ocean',
    title: 'OCEAN',
    artist: 'KAROL G',
    year: 2019,
    genre: 'Urbano latino',
    cover: 'assets/images/covers/ocean.jpg',
    palette: [0xFF7393AA, 0xFF73969A, 0xFFA4A199],
    tracks: [
      SampleTrack('ocean-1', 'Ocean', 154),
      SampleTrack('ocean-2', 'Punto G', 181),
      SampleTrack(
        'ocean-3',
        'Love With A Quality (feat. Damian "Jr. Gong" Marley)',
        222,
      ),
      SampleTrack('ocean-4', 'Baby', 238),
      SampleTrack('ocean-5', 'Sin Corazón', 169),
      SampleTrack('ocean-6', 'Dices Que Te Vas (feat. Anuel AA)', 204),
      SampleTrack('ocean-7', 'Pineapple', 178),
      SampleTrack('ocean-8', 'La Vida Continuó (feat. Simone & Simaria)', 165),
      SampleTrack('ocean-9', 'Bebesita', 183),
      SampleTrack('ocean-10', 'Culpables', 227),
      SampleTrack('ocean-11', 'Mi Cama', 151),
      SampleTrack('ocean-12', 'La Ocasión Perfecta (feat. Yandel)', 222),
      SampleTrack('ocean-13', 'Créeme', 212),
      SampleTrack('ocean-14', 'Go Karo', 148),
      SampleTrack('ocean-15', 'Mi Cama (feat. Nicky Jam) [Remix]', 196),
      SampleTrack('ocean-16', 'Yo Aprendí (feat. Danay Suárez)', 186),
    ],
  ),
  SampleAlbum(
    id: 'ram',
    title: 'Random Access Memories',
    artist: 'Daft Punk',
    year: 2013,
    genre: 'Pop',
    cover: 'assets/images/covers/ram.jpg',
    palette: [0xFF4E5764, 0xFF2B2A2C, 0xFF0B0E0E],
    tracks: [
      SampleTrack('ram-1', 'Give Life Back to Music', 274),
      SampleTrack('ram-2', 'The Game of Love', 322),
      SampleTrack('ram-3', 'Giorgio by Moroder', 545),
      SampleTrack('ram-4', 'Within', 229),
      SampleTrack('ram-5', 'Instant Crush', 338),
      SampleTrack('ram-6', 'Lose Yourself to Dance', 354),
      SampleTrack('ram-7', 'Touch', 499),
      SampleTrack('ram-8', 'Get Lucky', 370),
      SampleTrack('ram-9', 'Beyond', 290),
      SampleTrack('ram-10', 'Motherboard', 342),
      SampleTrack('ram-11', 'Fragments of Time', 280),
      SampleTrack('ram-12', 'Doin\' it Right', 251),
      SampleTrack('ram-13', 'Contact', 381),
    ],
  ),
  SampleAlbum(
    id: 'rainbows',
    title: 'In Rainbows',
    artist: 'Radiohead',
    year: 2007,
    genre: 'Alternativa',
    cover: 'assets/images/covers/rainbows.jpg',
    palette: [0xFFC17040, 0xFF7C5B30, 0xFF1D1A1F],
    tracks: [
      SampleTrack('rainbows-1', '15 Step', 237),
      SampleTrack('rainbows-2', 'Bodysnatchers', 242),
      SampleTrack('rainbows-3', 'Nude', 255),
      SampleTrack('rainbows-4', 'Weird Fishes / Arpeggi', 318),
      SampleTrack('rainbows-5', 'All I Need', 229),
      SampleTrack('rainbows-6', 'Faust Arp', 130),
      SampleTrack('rainbows-7', 'Reckoner', 290),
      SampleTrack('rainbows-8', 'House of Cards', 328),
      SampleTrack('rainbows-9', 'Jigsaw Falling Into Place', 249),
      SampleTrack('rainbows-10', 'Videotape', 280),
    ],
  ),
  SampleAlbum(
    id: 'slowrush',
    title: 'The Slow Rush',
    artist: 'Tame Impala',
    year: 2020,
    genre: 'Alternative',
    cover: 'assets/images/covers/slowrush.jpg',
    palette: [0xFFB91F08, 0xFFAF2810, 0xFF2F150F],
    tracks: [
      SampleTrack('slowrush-1', 'One More Year', 322),
      SampleTrack('slowrush-2', 'Instant Destiny', 194),
      SampleTrack('slowrush-3', 'Borderline', 238),
      SampleTrack('slowrush-4', 'Posthumous Forgiveness', 366),
      SampleTrack('slowrush-5', 'Breathe Deeper', 373),
      SampleTrack('slowrush-6', 'Tomorrow\'s Dust', 327),
      SampleTrack('slowrush-7', 'On Track', 302),
      SampleTrack('slowrush-8', 'Lost in Yesterday', 250),
      SampleTrack('slowrush-9', 'Is It True', 238),
      SampleTrack('slowrush-10', 'It Might Be Time', 273),
      SampleTrack('slowrush-11', 'Glimmer', 129),
      SampleTrack('slowrush-12', 'One More Hour', 433),
    ],
  ),
];
